### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by andyasp**
It's been over a month since the last build, so this is part of preparing for another one.
Summary:
  * `github.com/prometheus/client_golang` from `v1.15.1` to `v1.16.0`
  * `github.com/sirupsen/logrus` from `v1.9.2` to `v1.9.3`
  * `golang.org/x/sync` from `v0.2.0` to `v0.3.0`
  * `k8s.io/api` from `v0.27.2` to `v0.27.3`
  * `k8s.io/apimachinery` from `v0.27.2` to `v0.27.3`
  * `k8s.io/client-go` from `v0.27.2` to `v0.27.3`

### CODE REVIEW

**Comment by andyasp** [comment]
Seeing this failure in integration tests:

> Failed Cluster Start: error during post-start cluster preparation: error overwriting contents of /etc/hosts: docker failed to attach to exec process in node 'k3d-k3d-test-1689258604854-server-0': http: invalid Host header

Not sure why currently.

**Comment by andyasp** [comment]
The above issue is still ongoing. It's looking like docker will be releasing the fix in 24.0.5. An issue to reference is [here](https://www.github.com/moby/moby/issues/45935).

**Comment by andyasp** [comment]
Manually updating the indirect dependencies `docker/docker` and `docker/cli` to `v24.0.5` breaks k3d, so the fun train is still rolling.

**Comment by andyasp** [comment]
k3d released an update 10 hours ago so this is now unblocked.

**Review by pracucci — APPROVED** [review]
Patch versions for K8S, other dependency changes looks safe, so LGTM

**Review by 56quarters — APPROVED** [review]
I can't believe integration tests passed on the first try, thanks!

**Pull request merged**
