### PR TITLE
Enable publishing a multi-platform linux/amd64,linux/arm64 image

### LINKED ISSUE #16: ARM Support for docker image
Current rollout image does not have an arm64 compatible image

```
standard_init_linux.go:228: exec user process caused: exec format error
```

I just moved the build to the dockerfile using the builder pattern and use the builtin support for multi arch from `docker buidlx` 
```
FROM --platform=$BUILDPLATFORM golang:1.17-alpine AS builder

ADD . /app
WORKDIR /app

ARG TARGETOS
ARG TARGETARCH

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -ldflags="-s -w" ./cmd/rollout-operator

FROM alpine:3.14

COPY --from=builder /app/rollout-operator /bin/rollout-operator
ENTRYPOINT [ "/bin/rollout-operator" ]

# Create rollout-operator user to run as non-root.
RUN addgroup -g 10000 -S rollout-operator && \
    adduser  -u 10000 -S rollout-operator -G rollout-operator
USER rollout-operator:rollout-operator

ARG revision
LABEL org.opencontainers.image.title="rollout-operator" \
      org.opencontainers.image.source="https://github.com/grafana/rollout-operator" \
      org.opencontainers.image.revision="${revision}"
```

And to build just specify the architectures (Note arm builds require push ~ images aren't stored locally)

```
docker buildx build --platform linux/amd64,linux/arm64 --tag your-registry.tld/repo/grafana/rollout-operator:latest --push .
```

### PR DESCRIPTION
**Pull request by andyasp**
This is an attempt to enable publishing a multiplatform image while keeping the Makefile and Dockerfile relatively simple.

~I would like to figure out what's happening in https://github.com/grafana/rollout-operator/pull/39 before looking at this closely so `golang:1.20.1-bullseye` can be used as a build image.~ Done.

Fixes #16

### CODE REVIEW

**Comment by andyasp** [comment]
Depends on #39 then can be rebased.

**Comment by andyasp** [comment]
Integration failure appears to be what https://github.com/grafana/rollout-operator/pull/41 is fixing.

**Comment by andyasp** [comment]
Published a test image [here](https://hub.docker.com/layers/andyasp/rollout-operator/arm-build-141dbc2/images/sha256-dc237c6b847520cc931b9c4d6823770cf738daffa7fae9a72897d9829287f417?context=explore) to double check the publishing step and it ran fine on a local helm install with an arm64 node.

**Review by 56quarters — APPROVED** [review]
LGTM

**Pull request merged**
